### ISSUE TITLE
Connection to k8s master was leaked

### ISSUE THREAD

**Issue by sanjana-bhat** [fabric8io/kubernetes-client#294] opened 2016-01-27 23:53 UTC
Hi,

We recently upgraded kubernetes-api version from 2.2.50 to 2.2.85 to pull in some of the rolling update API changes. After doing an upgrade I see the following warnings in the logs:
[OkHttp ConnectionPool] WARN  com.squareup.okhttp.OkHttpClient - A connection to http://k8s_host:k8s_port/ was leaked. Did you forget to close a response body?

@iocanel I see that the older version was using AsyncHttpClient which never threw these warnings. Is this a bug with the new changes?

Thanks,
Sanjana

**Comment by iocanel** [comment] 2016-01-28 08:15
Thanks for reporting it.

I am not sure if the leak was introduced lately, or its just the warning :-)

I'll have a look asap.

**Comment by jimmidyson** [comment] 2016-01-28 08:21
It's an enhancement in latest okhttp so likely the leak was always there but not reported.

**Comment by jimmidyson** [comment] 2016-01-28 08:59
Oops looks like we always forget to close the response body... looking at fixing now.

**Comment by jimmidyson** [comment] 2016-01-28 09:03
Hmm no looks like Jackson's `ObjectMapper.readValue` does close the `InputStream` so struggling to find where the leak is from.

**Comment by jimmidyson** [comment] 2016-01-28 09:13
@sanjana-bhat Can you share a small bit of code that reproduces the log message? I've found a couple of places we haven't closed the body properly, but not sure they would  fix the leak in your case.

**Comment by sanjana-bhat** [comment] 2016-01-28 19:02
@jimmidyson 
I don't see these warnings all the time but they are intermittent. This is how I initialize the client and I never close it. I'm using this in my API server.
```
private static KubernetesClient client;
public KubeClient(final String masterUrl) {
    client = new DefaultKubernetesClient(masterUrl);
}
```

**Comment by sanjana-bhat** [comment] 2016-02-10 00:42
@iocanel @jimmidyson any updates on this?

**Comment by WinstonSureChill** [comment] 2016-02-10 08:20
I'm facing this issue too.

**Comment by iocanel** [comment] 2016-02-10 09:29
@sanjana-bhat @WinstonSureChill: I don't have something from my side. I mistakenly thought/hoped that @jimmidyson commits fixed the issue completely. Will have a look.

**Comment by jimmidyson** [comment] 2016-02-10 10:40
Any code to reproduce the issue would be appreciated, as would trace logging to help find what's causing it.

**Comment by WinstonSureChill** [comment] 2016-02-15 15:07
i'm running kubernetes-api 2.2.91 and the exact warning I'm encoutering is this one:

```
Feb 15, 2016 3:50:42 PM com.squareup.okhttp.ConnectionPool pruneAndGetAllocationCount
WARNING: A connection to http://localhost:8080/ was leaked. Did you forget to close a response body?
```

I'm pretty busy now so I can't really take the time to build a minimal test case, but basically it happens to me during unit tests, where I create/remove pods/svc/rc, sometimes on a pretty short schedule.

I'll try to write a minimal test case when I have some time.

**Comment by jimmidyson** [comment] 2016-02-21 10:42
Does this only happen when you're using watch or other times? Think there is a problem with https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java#L166 preventing the previous call from closing as we're opening another call on the same thread as the close callback. Fix appreciated :)

**Comment by jimmidyson** [comment] 2016-02-21 10:46
Any thoughts on above @rouzwawi?

**Comment by rouzwawi** [comment] 2016-02-21 14:45
@jimmidyson That sounds plausible. I can attempt a fix later today.

**Comment by jimmidyson** [comment] 2016-03-10 13:28
PR in #330 - review / trying it out would be good.

**Comment by tomason** [comment] 2016-03-14 13:57
I have tried it out today as it was merged into master. Built the master branch (7cdb50bb5ba95c2b7b86cdd92f879b43567a6300) and the warning is still present (although there are less of them). I'm using OpenShiftClient class as follows:

OpenShiftConfig config = new OpenShiftConfigBuilder()
					.withMasterUrl(TestConfiguration.masterUrl())
					.withTrustCerts(true)
					.withUsername("username")
					.withPassword("pwd123")
					.withNamespace("my-project")
					.build();
new DefaultOpenShiftClient(config)

And I think, that the warning is throw every time I send the first request (i.e. when requesting token from the server).

**Comment by jimmidyson** [comment] 2016-03-14 14:51
@tomason Thanks for the report - fixed that up too now... it was a special case for OpenShift auth that I missed. Hope that's it now :)

**Comment by tomason** [comment] 2016-03-14 17:48
Yes, the latest version does not print any more warnings. Thanks for fixing this!

**Comment by jimmidyson** [comment] 2016-03-14 17:49
Awesome! Closing now - feel free to reopen if there you see it again.

**Closed by jimmidyson** 2016-03-14 17:49 UTC
