### ISSUE TITLE
How can I get Kubernetes version using kubernetes-client?

### ISSUE THREAD

**Issue by fecogc** [fabric8io/kubernetes-client#349] opened 2016-03-30 07:57 UTC
How can I get Kubernetes version using kubernetes-client api

**Comment by jimmidyson** [comment] 2016-03-30 08:15
Is the Kubernetes version available from the Kubernetes REST API? I'm not sure that it is but if it is we're happy to receive contribution to add it to this client.

**Comment by fecogc** [comment] 2016-03-31 05:56
The version is available in the swagger ui,

http://(master-url)/version

**Comment by jimmidyson** [comment] 2016-03-31 07:55
So the output is in the format (for a dev build at least):

```json
{
  "major": "1",
  "minor": "3+",
  "gitVersion": "v1.3.0-alpha.1.56+2e89f555c650c0",
  "gitCommit": "2e89f555c650c01ba577a015fd1b23dbb71707e3",
  "gitTreeState": "clean",
  "buildDate": "2016-03-31T07:47:47Z",
  "goVersion": "go1.6",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

Does that have all the data you need?

**Comment by fecogc** [comment] 2016-03-31 09:38
yes! perfect, thats all what I need :)

**Comment by jimmidyson** [comment] 2016-06-16 09:42
PR welcome if you anyone has time.

**Comment by gjw0317** [comment] 2017-06-07 04:12
Has this be added to the client? If yes, how can I get Kubernetes version using kubernetes-client api?

**Comment by rohanKanojia** [comment] 2018-12-27 16:35
@fecogc @gjw0317 : Yes, it has been added. Please see example:https://github.com/fabric8io/kubernetes-client/blob/a909fda0daf0ad91ccd02e2f02c66f47d33f54d0/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/KubernetesVersionExample.java#L32-L40

**Comment by rohanKanojia** [comment] 2018-12-27 16:38
Duplicate of #1048

**Closed by rohanKanojia** 2018-12-27 16:38 UTC
Labels: help wanted
