### ISSUE TITLE
Upgrade Fabric8 Kubernetes Model to Kubernetes v1.26

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#4655] opened 2022-12-12 05:44 UTC
### Description

Kubernetes 1.26 was [released](https://www.kubernetes.dev/resources/release/) on 2022-12-09. Our model should be updated, including any new types and DSL access for new resources.

- https://kubernetes.io/releases/
- https://kubernetes.io/blog/2022/12/09/kubernetes-v1-26-release/
- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.26.md
- https://github.com/kubernetes/kubernetes/releases/tag/v1.26.0

**Comment by rohanKanojia** [comment] 2022-12-12 05:53
Duplicate of https://github.com/fabric8io/kubernetes-client/issues/4652

**Closed** 2023-02-06 11:30 UTC
Labels: dependencies, component/kubernetes-client, component/kubernetes-model
