### ISSUE TITLE
Compile failures since 6.9.1 (io.fabric8.kubernetes.api.builder.Editable not found)

### ISSUE THREAD

**Issue by k-wall** [fabric8io/kubernetes-client#5617] opened 2023-11-27 11:49 UTC
### Describe the bug

Our projects trying to upgrade from 6.8.1 to 6.9.2 (https://github.com/kroxylicious/kroxylicious/pull/745).  It is suffering a compile failure.  Bisecting shows that 6.9.0 was okay, but 6.9.1 introduces the problem.

```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/kwall/src/kroxylicious/kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/resources/kroxylicious/KroxyliciousServiceResource.java:[26,65] cannot access io.fabric8.kubernetes.api.builder.Editable
  class file for io.fabric8.kubernetes.api.builder.Editable not found
[ERROR] /Users/kwall/src/kroxylicious/kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/k8s/KubeClient.java:[97,46] cannot access io.fabric8.kubernetes.api.builder.VisitableBuilder
  class file for io.fabric8.kubernetes.api.builder.VisitableBuilder not found
[ERROR] /Users/kwall/src/kroxylicious/kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/DeploymentUtils.java:[105,17] cannot access io.fabric8.kubernetes.api.builder.BaseFluent
  class file for io.fabric8.kubernetes.api.builder.BaseFluent not found
[ERROR] /Users/kwall/src/kroxylicious/kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/templates/kroxylicious/KroxyliciousDeploymentTemplates.java:[43,17] cannot access io.fabric8.kubernetes.api.builder.Nested
  class file for io.fabric8.kubernetes.api.builder.Nested not found
[ERROR] /Users/kwall/src/kroxylicious/kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/installation/kroxylicious/CertManager.java:[45,19] cannot access io.fabric8.kubernetes.api.builder.Visitable
  class file for io.fabric8.kubernetes.api.builder.Visitable not found
[INFO] 5 errors
```

### Fabric8 Kubernetes Client version

6.9.2

### Steps to reproduce

1. `git clone git@github.com:kroxylicious/kroxylicious.git`
2. `git checkout upstream/dependabot/maven/fabric8.kubernetes.version-6.9.2`
3. `mvn -X clean compile  -pl kroxylicious-systemtests` (fails with the compile error)

If you change the kubernetes client back to 6.9.0 the problem disappears.

`mvn -X clean compile -pl kroxylicious-systemtests -Dfabric8.kubernetes.version=6.9.0` (compiles okay)

### Expected behavior

No compile failure.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

**Comment by manusa** [comment] 2023-11-27 11:54
You very likely have a dependency to Sundrio in your project that's not aligned with the client's.

Code generated by the most recent versions of Sundrio and the ones we depended on for 6.8 are not compatible (this shouldn't be the case for future releases).

Please, make sure that your sundrio dependency is on version `0.101.3` and let us know if the problem persists.

**Comment by k-wall** [comment] 2023-11-27 12:08
@manusa  you replied (thank you) before I was done editing the description.  There's more information there now.

I confirm that I still see the issue with sundrio 0.101.3.

```
[INFO] +- io.sundr:builder-annotations:jar:0.101.3:provided
[INFO] |  +- io.sundr:sundr-codegen-apt:jar:0.101.3:provided
[INFO] |  |  +- io.sundr:sundr-codegen-api:jar:0.101.3:provided
[INFO] |  |  \- io.sundr:sundr-adapter-apt:jar:0.101.3:provided
[INFO] |  |     \- io.sundr:sundr-model-utils:jar:0.101.3:provided
[INFO] |  +- io.sundr:sundr-adapter-reflect:jar:0.101.3:provided
[INFO] |  |  +- io.sundr:sundr-model:jar:0.101.3:provided
[INFO] |  |  |  +- io.sundr:sundr-core:jar:0.101.3:provided
[INFO] |  |  |  \- io.sundr:sundr-model-base:jar:0.101.3:provided
[INFO] |  |  \- io.sundr:sundr-adapter-api:jar:0.101.3:provided
[INFO] |  |     \- io.sundr:sundr-model-repo:jar:0.101.3:provided
[INFO] |  \- io.sundr:resourcecify-annotations:jar:0.101.3:provided
```

**Comment by andreaTP** [comment] 2023-11-27 12:26
I can reproduce the issue, it might be caused by the fact that they are using Java 21 ... I knocked on the wood ... 😅 

@k-wall do you expect `kroxylicious-integration-test-support` to be exposed to the user?
I don't see much usage of `sundrio` around, just a couple of Builder patterns, would you consider rolling those `Builder`s manually?

**Comment by shawkins** [comment] 2023-11-27 12:59
The issue is that strimzi is pulling in the older kubernetes-model-common:

```

**Comment by k-wall** [comment] 2023-11-27 13:21
@shawkins thank you, you are right.  That is the issue.   I ought to have spotted that myself.

**Comment by shawkins** [comment] 2023-11-27 13:25
> thank you, you are right. That is the issue. I ought to have spotted that myself.

No problem.  Unfortunately we needed to move those repackaged fabric8 classes to accomodate adding an edit/toBuilder method directly to the model pojos.  At least for now we'll probably require everything to stay aligned.

**Comment by manusa** [comment] 2023-11-27 14:04
OK, I see now, 

> The issue is that strimzi is pulling in the older kubernetes-model-common:
> 
> ```
> [INFO] +- io.strimzi:api:jar:0.37.0:compile
> [INFO] |  +- io.fabric8:kubernetes-model-common:jar:6.8.1:compile
> ```

Thanks for checking it out, I was just to clone the project and investigate the problem :ok_hand:

**Comment by manusa** [comment] 2023-11-27 14:05
I'm closing the issue, since it's a convergence error.
Not sure if Strimzi has already a release with the updated Kubernetes Client version.

**Closed by manusa** 2023-11-27 14:05 UTC

**Comment by shawkins** [comment] 2023-11-27 14:07
@manusa @k-wall I don't think there would be any problem with forcing the strimzi dependency to use the newer kubernetes-model-common if you don't want to wait for another release.

**Comment by andreaTP** [comment] 2023-11-27 15:15
An alternative, to decouple from Strimzi releases, would be to use the Java Generator.
But I trust that handwritten code is probably more idiomatic than the generated counterpart.
