### ISSUE TITLE
updateStatus() to no longer work as with mock server in CRUD mode

### ISSUE THREAD

**Issue by gdauchet** [fabric8io/kubernetes-client#3383] opened 2021-08-06 15:26 UTC
updateStatus() to no longer work as with mock server in CRUD mode as it generates a JSON_MERGE_PATCH patch type which is not handled

**Comment by shawkins** [comment] 2021-08-06 16:56
This is a duplicate of #3379

**Comment by gdauchet** [comment] 2021-08-09 12:22
Clsoed as duplicate to 3379

**Closed** 2021-08-09 12:22 UTC
