### ISSUE TITLE
Using DeleteOptions when deleting a resource

### ISSUE THREAD

**Issue by mpuyat** [fabric8io/kubernetes-client#284] opened 2016-01-14 19:55 UTC
Maybe I missed this when looking through the code... but I don't see a way to delete a resource while specifying the `DeleteOptions` like the `graceSeconds` we want to use.

If this is already something that is doable, would be great if we could include an example of how to do this in the [DeleteExamples](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/DeleteExamples.java)

**Comment by sarvigalava** [comment] 2016-02-29 15:40
I'm also searching for this functionality :+1:

**Comment by jimmidyson** [comment] 2016-02-29 15:46
This is not currently implemented. We'd love it to be added though - contribution would be very welcome.

**Comment by sarvigalava** [comment] 2016-03-07 08:03
I am working on this, please assign it to me. (Sorry, I am new to github, I guess I have to create a new branch for this, have I ?)

**Comment by sarvigalava** [comment] 2016-03-07 08:34
I've created the branch  'delete-options' and commited the initial implementation for this.
I managed to add the parameter for deletion of pod using its name. Currently I am working to integrate it with bulk deletion (using selectors).

**Comment by jimmidyson** [comment] 2016-03-07 08:43
@sarvigalava Sounds good! Thanks for working on this.

**Comment by sarvigalava** [comment] 2016-03-07 10:38
An approach like this : client.pods().withGracePeriod(n).withLabel()....delete() is ok ?

The problem is I cannot implement the Filterable interface for the second time due to type erasure :(

I have to pass the parameter before filtering to reuse the existing functionality without any major changes

**Comment by sarvigalava** [comment] 2016-03-07 11:06
or :
1. client.configBulkDelete().withGracePeriod(n).withLabel(l)... delete()
2. client.configBulkDelete.withLabel(l)...[withGracePeriod(n) -- optional].delete()

P.S. The previous approach causes another type clashing

**Comment by jimmidyson** [comment] 2016-03-07 11:37
How about adding grace period to `Config` so it can be set on a per-client basis rather than per-call as well? Override in DSL?

Grace period is applicable for pods & replication controller deletion, I guess also DaemonSets & PetSets moving forward too. So perhaps the DSL makes sense adding in `Deletable`? Those resources that don't need grace period can ignore the setting?

@iocanel - Mr DSL - what do you think?

**Comment by iocanel** [comment] 2016-03-07 13:00
I wouldn't add something to Deleteable unless it applies globally or I am out of options.

 I would prefer

    client.pods().withLabel()....withGracePeriod(n).delete();

over

    client.pods().withGracePeriod(n).withLabel()....delete()

Why?

Because DSL and implementation wise the custom options are better placed at the end of the invocation chain. In fact I don't think that its even possible otherwise.

**Comment by jimmidyson** [comment] 2016-03-07 13:06
So a new interface to add the grace period option as required? `GracePeriodable` sounds awful :)

**Comment by sarvigalava** [comment] 2016-03-07 13:07
actually it is GracePeriodConfigurable :D

**Comment by jimmidyson** [comment] 2016-03-07 13:08
^^^ phew that's much better!

**Comment by sarvigalava** [comment] 2016-03-07 13:08
I've added GracePeriodConfigurable<Deletable<B>> to intefaces that extend Deletable<B> like :

public interface EditReplaceDeletable<I, T, D, B> extends EditReplaceable<I, T, D>, Deletable<B>,
                                                          GracePeriodConfigurable<Deletable<B>>

**Comment by sarvigalava** [comment] 2016-03-07 13:10
As I see in the Kubernetes API doc, all delete endpoints support DeleteOptions as BodyParam, so it will be ok if we add this to all Operations if the parameter is set (>= 0)

**Comment by jimmidyson** [comment] 2016-03-07 13:13
Nice work.

**Comment by sarvigalava** [comment] 2016-03-07 13:14
thx :)

**Comment by sarvigalava** [comment] 2016-03-07 14:32
I'm done with implementation, could someone review my changes ?

**Comment by jimmidyson** [comment] 2016-03-07 20:04
Fixed by #321 - thanks again!

**Closed by jimmidyson** 2016-03-07 20:04 UTC
