### ISSUE TITLE
Request to release 4.1.2

### ISSUE THREAD

**Issue by Jeffwan** [fabric8io/kubernetes-client#1358] opened 2019-02-14 21:39 UTC
Notice several PRs were merged into master since 4.1.1. Can we have another release? 
I really like to get rid of the following issue which has already been resolved on master. 

Issue: 
https://github.com/fabric8io/kubernetes-client/issues/1332

PR:
https://github.com/fabric8io/kubernetes-client/pull/1333

**Comment by Jeffwan** [comment] 2019-02-14 21:39
@rohanKanojia

**Comment by candyleer** [comment] 2019-02-15 05:17
+1 hope for 4.1.2 wait some fixed bug....

**Comment by rohanKanojia** [comment] 2019-02-15 09:39
@Jeffwan @candyleer : Would make a release this weekend, Actually I was waiting for some regressions to get fixed by #1322 , but I think it's quite a while since the last release

**Comment by Jeffwan** [comment] 2019-02-15 18:41
Excellent! Look forward to the new version!

**Comment by rohanKanojia** [comment] 2019-02-16 08:01
@Jeffwan @candyleer : I've published 4.1.2, it can be found [here](https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/4.1.2/). Sorry for the dealy and thanks for your patience. Please try it out and share feedback ;-)

**Closed** 2019-02-16 08:01 UTC

**Comment by Jeffwan** [comment] 2019-02-17 06:11
Great! Thanks a lot! @rohanKanojia

**Comment by skonto** [comment] 2019-02-27 11:16
fyi I have filed this one: https://github.com/fabric8io/kubernetes-client/issues/1376
