### ISSUE TITLE
Knative Services always have .status as null

### ISSUE THREAD

**Issue by FWiesner** [fabric8io/kubernetes-client#2185] opened 2020-05-01 21:05 UTC
Observed this on both Watches as well as when getting the Services via the API. `.status` is always deserialized to null

**Comment by rohanKanojia** [comment] 2020-05-02 06:36
Duplicate of #2117

**Comment by rohanKanojia** [comment] 2020-05-02 06:37
@FWiesner : Which version are you using? Could you please try on v4.9.1?

**Comment by FWiesner** [comment] 2020-05-02 10:17
I'm on 4.9.1

**Comment by rohanKanojia** [comment] 2020-05-02 10:42
Strange, I remember this was fixed in #2120 . We already have a test in place to check this:

https://github.com/fabric8io/kubernetes-client/blob/deddbaaf702413a40c4429c50d4e3906f2c26ec4/extensions/knative/tests/src/test/java/io/fabric8/knative/test/crud/ServiceCrudTest.java#L62-L80

**Comment by FWiesner** [comment] 2020-05-02 11:03
ok, then I assume that we had a problem with the upgrade from 4.9.0 to 4.9.1

**Comment by FWiesner** [comment] 2020-05-02 11:06
yeah, that was the problem... thanks @rohanKanojia

**Closed** 2020-05-02 11:06 UTC
