### ISSUE TITLE
OpenShiftServer in CRUD mode returns all objects regardless of query

### ISSUE THREAD

**Issue by anderssv** [fabric8io/kubernetes-client#936] opened 2017-12-06 12:27 UTC
I'm writing some tests and wanted to use OpenShiftServer with CRUD mode enabled. It seems to return all the objects regardless of the type/query I give the client.

I did some debugging and I think the culprit is because OpenShiftMockServer is instantiated with a  KubernetesAttributesExtractor which doesn't match the "/oapi/*" URLs (it matches "/api/*") so the query attributes are always blank.

**Comment by piyush1594** [comment] 2018-08-28 13:46
This is duplicate of #1144  and has been resolved with #1145

**Closed by piyush1594** 2018-08-28 13:46 UTC
