### ISSUE TITLE
Integration test suite 

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/kubernetes-client#427] opened 2016-05-27 07:06 UTC
Should have thought about this from the start but now this library has a reasonable amount of usage we need an integration test suite to try to prevent regressions as well as testing against multiple versions of kubernetes & openshift. Hopefully most of the general crud operations tests can be generated. This is going to need resources to run on of course.

**Comment by rohanKanojia** [comment] 2018-12-27 16:44
Duplicate of #955

**Closed by rohanKanojia** 2018-12-27 16:44 UTC
