### ISSUE TITLE
Cannot create a Task using the Tekton extension

### ISSUE THREAD

**Issue by jeffmaury** [fabric8io/kubernetes-client#1900] opened 2019-12-09 18:03 UTC
I am trying to create a Task from this payload:

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-world1
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"

```

I always go rejected by the server and noticed that various attributes for the step are stored as additionalProperties and are lost when editing the resource.
I looked at the code and noticed that the Step model class is defined as containing a Container where it is an extension of Container (from the Go code).

**Comment by rohanKanojia** [comment] 2019-12-09 18:10
Our Model currently supports v0.7.0. Which tekton version are you using? There is one PR #1891 to upgrade model, it should make into next release.

**Comment by jeffmaury** [comment] 2019-12-09 22:41
I'm using 0.7.0. But the model is broken for me. See https://github.com/tektoncd/pipeline/blob/v0.7.0/pkg/apis/pipeline/v1alpha1/task_types.go#L68 and compare to the Step class from the model and you will understand the problem.

**Comment by Fabian-K** [comment] 2019-12-10 12:02
Yep, this is a different issue. It looks like that the generator does not support embedding structs. Something like 
```
type Step struct {
	corev1.Container
}
```
should in the end not have an intermediate property container but instead union all properties of the embedded struct.

Does this make sense?

Also in 0.9.0 this will be extended with an additional field "script" (see https://github.com/tektoncd/pipeline/blob/v0.9.0/pkg/apis/pipeline/v1alpha1/task_types.go#L66-L73).

**Comment by rohanKanojia** [comment] 2020-01-09 13:25
@jeffmaury  @Fabian-K : We released [v4.7.0](https://search.maven.org/search?q=g:io.fabric8%20AND%20a:tekton-model) yesterday which should have updated tekton model. Could you please check if this issue can be resolved with this?

**Comment by Fabian-K** [comment] 2020-01-13 16:28
@rohanKanojia in our setup we are not creating tasks so I didn´t verify it. Release 4.7.0 fixes an issue when creating pipeline runs (e.g. due to the change from the field serviceAccount to serviceAccoutName in PipelineRuns - I can confirm that :) ). It however most likely does not fix this issue

**Comment by rohanKanojia** [comment] 2020-01-13 16:31
ah, okay. Thanks

**Closed** 2020-03-02 14:44 UTC
