### ISSUE TITLE
How to do a rolling update to a deployment

### ISSUE THREAD

**Issue by coderDemo** [fabric8io/kubernetes-client#1281] opened 2018-11-28 07:09 UTC
How to do a rolling update  a deployment
just change the image versoin

**Comment by VitZhou** [comment] 2019-02-10 08:05
I also encountered the same problem

**Comment by rohanKanojia** [comment] 2019-02-11 05:56
Duplicate of #1064

**Closed** 2019-02-11 05:56 UTC

**Comment by coderDemo** [comment] 2019-02-12 01:47
do like this
`        kubernetesClient.apps().deployments().inNamespace(namespace).withName(serviceToUpdate)
                .edit().editSpec()
                .editTemplate().editSpec().editContainer(0).withImage(newImage).endContainer().endSpec()
                .endTemplate().endSpec().done();
`

**Comment by coderDemo** [comment] 2019-02-12 01:48
@VitZhou
