### ISSUE TITLE
client.load(new FileInputStream(args[0])).createOrReplace(); throws nullPointer for "generateName"

### ISSUE THREAD

**Issue by ajaygk95** [fabric8io/kubernetes-client#1373] opened 2019-02-27 07:53 UTC
If the pod-spec.yaml contains `generateName` tag then createOrReplace() is throwing the below exception.

java.lang.NullPointerException
    at java.net.URI$Parser.parse(URI.java:3042)
    at java.net.URI.<init>(URI.java:588)
    at io.fabric8.kubernetes.client.utils.URLUtils.join(URLUtils.java:48)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:208)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:177)
    at io.fabric8.kubernetes.client.handlers.PodHandler.reload(PodHandler.java:53)
    at io.fabric8.kubernetes.client.handlers.PodHandler.reload(PodHandler.java:32)
    at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:202)
    at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:62)
    at com.nokia.k8s.InterpreterLanuch.main(InterpreterLanuch.java:66)

**Comment by ajaygk95** [comment] 2019-02-27 07:55
Discussion available in [1299](https://github.com/fabric8io/kubernetes-client/issues/1299)

**Comment by rohanKanojia** [comment] 2019-03-01 09:01
@ajaygk95 @max5599: I'm not able to reproduce this issue. This is what I tried:
1.) Load this yaml via client and post to cluster:
```
apiVersion: v1
kind: Pod
metadata:
  generateName: zep-ag-pod
  annotations:
    kubernetes.io/psp: restricted
    spark-app-name: Zeppelin-spark-shared-process
  labels:
    app: zeppelin
    int-app-selector: shell-123
spec:
  containers:
    - name: ag-csf-zep
      image: bcmt-registry:5000/zep-spark2.2:9
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash"]
      args: ["-c","echo Hi && sleep 60 && echo Done"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
  securityContext:
    fsGroup: 2000
    runAsUser: 1510
```
2.) Code used to creating a pod:
```
      Pod aPod = client.pods().inNamespace("myproject").load(HorizontalPodAutoscaler.class.getResourceAsStream("/test-pod.yml")).get();
      client.pods().inNamespace("myproject").create(aPod);
```

After executing this, I was able to see pod being created : 
```
~/work/resouce-yamls : $ oc get pods
NAME              READY     STATUS         RESTARTS   AGE
zep-ag-podm8bfm   0/1       ErrImagePull   0          8s
```

Have I understood the bug correctly? It's about `generateName` or is it about Role?

**Comment by max5599** [comment] 2019-03-01 18:24
I was using `createOrReplace` that was working with version 3.1.8 but it's not working anymore with the latest version.
I think it make sense as the use of a `generate-name` is to create a unique pod.
@ajaygk95 were you using `createOrReplace` too?

**Comment by ajaygk95** [comment] 2019-03-04 10:41
Sorry for the late reply. In my case i have an resource-spec.yaml which contains multiple resources like "pod", "service" and "role". So i am using `createOrReplace` with my resource-spec.yaml.
If the "pod" resource has `generateName` then i get the nullpointwer exception

**Comment by rohanKanojia** [comment] 2019-03-07 11:39
@ajaygk95 @max5599 : okay, I tested with `createOrReplace()` and yes it fails with this error:
```
17:08:54.940 [main] ERROR io.fabric8.kubernetes.examples.CreatePod - Name must be provided.
java.lang.IllegalArgumentException: Name must be provided.
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withName(BaseOperation.java:276) ~[classes/:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:437) ~[classes/:?]
	at io.fabric8.kubernetes.examples.CreatePod.main(CreatePod.java:83) [classes/:?]
```

We just need to loosen the validation done there in order to adjust generateName.

**Comment by rohanKanojia** [comment] 2019-04-01 05:22
By loosening the validation, I mean we should ignore name in case generateName is provided here: https://github.com/fabric8io/kubernetes-client/blob/ebe2de35922ae4b1477edbff6d2f20faacb9af4d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L252-L258

**Comment by rohanKanojia** [comment] 2019-04-19 08:49
@kunal-kushwaha : Would you like to work on this?

**Comment by kunal-kushwaha** [comment] 2019-04-19 09:21
@rohanKanojia Yes, I'm trying to reproduce this error. What exactly is the use for generateName? Also is it an option to pass some default name rather than throwing an exception?

**Comment by rohanKanojia** [comment] 2019-04-19 09:58
generateName generates a random name like specified in field. Yes, passing default name rather than throwing exception seems like an acceptable solution to me.

**Comment by kunal-kushwaha** [comment] 2019-04-19 11:16
I was thinking about generating a random name in the method itself incase the name is null.

**Comment by rohanKanojia** [comment] 2019-05-06 17:12
Please go through my comment [here](https://github.com/fabric8io/kubernetes-client/pull/1498#pullrequestreview-234092169). I think we can close this.

**Closed by rohanKanojia** 2019-05-06 17:12 UTC
Labels: bug, low hanging fruit
