### ISSUE TITLE
OkHttp responses not closed properly

### ISSUE THREAD

**Issue by scholzj** [fabric8io/kubernetes-client#4666] opened 2022-12-12 21:06 UTC
### Describe the bug

With 6.3.0 release, it seems that some OkHttp client responses are not closed properly and every 5 minutes, we get bunch of warnings about them in our logs in the Strimzi project For example:
* From leader election:
  ```
  2022-12-12 20:10:17 WARN  OkHttpClient:134 - A connection to https://10.96.0.1/ was leaked. Did you forget to close a response body?
  java.lang.Throwable: response.body().close()
	  at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:148) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
	  at okhttp3.RealCall.captureCallStackTrace(RealCall.java:116) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
	  at okhttp3.RealCall.enqueue(RealCall.java:125) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
	  at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl.sendAsync(OkHttpClientImpl.java:266) ~[io.fabric8.kubernetes-httpclient-okhttp-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl.consumeBytesDirect(OkHttpClientImpl.java:322) ~[io.fabric8.kubernetes-httpclient-okhttp-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.http.StandardHttpClient.consumeBytes(StandardHttpClient.java:57) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.http.SendAsyncUtils.bytes(SendAsyncUtils.java:51) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.http.HttpResponse$SupportedResponses.sendAsync(HttpResponse.java:105) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.http.HttpClient.sendAsync(HttpClient.java:178) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:618) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:595) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:570) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleUpdate(OperationSupport.java:366) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleUpdate(BaseOperation.java:709) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$replace$0(HasMetadataOperation.java:167) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.replace(HasMetadataOperation.java:172) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.replace(HasMetadataOperation.java:113) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.replace(HasMetadataOperation.java:41) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.replace(BaseOperation.java:1077) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.replace(BaseOperation.java:93) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.extended.leaderelection.resourcelock.LeaseLock.update(LeaseLock.java:100) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.tryAcquireOrRenew(LeaderElector.java:214) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.lambda$renewWithTimeout$6(LeaderElector.java:175) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.lambda$loop$8(LeaderElector.java:258) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	  at java.lang.Thread.run(Thread.java:833) ~[?:?]
  ```
* When creating a custom resource
  ```
  2022-12-12 20:35:07,81611 WARN  [OkHttp ConnectionPool] OkHttpClient:134 - A connection to https://10.96.0.1/ was leaked. Did you forget to close a response body?
  java.lang.Throwable: response.body().close()
	  at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:148) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
	  at okhttp3.RealCall.captureCallStackTrace(RealCall.java:116) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
	  at okhttp3.RealCall.enqueue(RealCall.java:125) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
	  at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl.sendAsync(OkHttpClientImpl.java:266) ~[io.fabric8.kubernetes-httpclient-okhttp-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl.consumeBytesDirect(OkHttpClientImpl.java:322) ~[io.fabric8.kubernetes-httpclient-okhttp-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.http.StandardHttpClient.consumeBytes(StandardHttpClient.java:57) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.http.SendAsyncUtils.bytes(SendAsyncUtils.java:51) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.http.HttpResponse$SupportedResponses.sendAsync(HttpResponse.java:105) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.http.HttpClient.sendAsync(HttpClient.java:178) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:618) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:595) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:570) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:554) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleCreate(OperationSupport.java:347) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:704) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:93) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:42) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:1107) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:93) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.strimzi.operator.topic.K8sImpl.lambda$createResource$0(K8sImpl.java:53) ~[io.strimzi.topic-operator-0.33.0-SNAPSHOT.jar:0.33.0-SNAPSHOT]
	  at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137) ~[io.vertx.vertx-core-4.3.5.jar:4.3.5]
	  at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264) ~[io.vertx.vertx-core-4.3.5.jar:4.3.5]
	  at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135) ~[io.vertx.vertx-core-4.3.5.jar:4.3.5]
	  at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-4.3.5.jar:4.3.5]
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	  at java.lang.Thread.run(Thread.java:833) ~[?:?]
  ```
* When updating CR status subresource:
  ```
  2022-12-12 20:35:07,81724 WARN  [OkHttp ConnectionPool] OkHttpClient:134 - A connection to https://10.96.0.1/ was leaked. Did you forget to close a response body?
  java.lang.Throwable: response.body().close()
	  at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:148) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
	  at okhttp3.RealCall.captureCallStackTrace(RealCall.java:116) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
	  at okhttp3.RealCall.enqueue(RealCall.java:125) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
	  at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl.sendAsync(OkHttpClientImpl.java:266) ~[io.fabric8.kubernetes-httpclient-okhttp-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl.consumeBytesDirect(OkHttpClientImpl.java:322) ~[io.fabric8.kubernetes-httpclient-okhttp-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.http.StandardHttpClient.consumeBytes(StandardHttpClient.java:57) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.http.SendAsyncUtils.bytes(SendAsyncUtils.java:51) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.http.HttpResponse$SupportedResponses.sendAsync(HttpResponse.java:105) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.http.HttpClient.sendAsync(HttpClient.java:178) ~[io.fabric8.kubernetes-client-api-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:618) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:595) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:570) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleUpdate(OperationSupport.java:366) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleUpdate(BaseOperation.java:709) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$replace$0(HasMetadataOperation.java:167) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.replace(HasMetadataOperation.java:172) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.replaceStatus(HasMetadataOperation.java:118) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.replaceStatus(HasMetadataOperation.java:41) ~[io.fabric8.kubernetes-client-6.3.0.jar:?]
	  at io.strimzi.operator.common.operator.resource.CrdOperator.lambda$updateStatusAsync$2(CrdOperator.java:132) ~[io.strimzi.operator-common-0.33.0-SNAPSHOT.jar:0.33.0-SNAPSHOT]
	  at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137) ~[io.vertx.vertx-core-4.3.5.jar:4.3.5]
	  at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264) ~[io.vertx.vertx-core-4.3.5.jar:4.3.5]
	  at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135) ~[io.vertx.vertx-core-4.3.5.jar:4.3.5]
	  at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-4.3.5.jar:4.3.5]
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	  at java.lang.Thread.run(Thread.java:833) ~[?:?]
  ```
* There seem to be more around list and get operations as well.

This was also discussed [here](https://github.com/fabric8io/kubernetes-client/discussions/4660#discussioncomment-4382702)

### Fabric8 Kubernetes Client version

6.3.0

### Steps to reproduce

Just using the Fabric8 Kubernetes client. If needed, I can try to create some reproducer code snippets. But it seems to come from all kind of places. The stacktraces are in the description.

### Expected behavior

No warnings about unclosed messages will appear in the logs.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
See the description. I can provide more logs if needed.
```

### Additional context

n/a

**Comment by manusa** [comment] 2022-12-13 05:08
:( it seems we might have introduced a regression when refactoring our OkHttp HttpClient implementation. We'll need to release a patch with a fix.

**Comment by manusa** [comment] 2022-12-13 06:46
Continues discussion in https://github.com/fabric8io/kubernetes-client/discussions/4660#discussioncomment-4383403

I'm not sure that the handler causing the leakage is the one for the `AsyncBody` (`sendAsync`) consumption. It is reported there as a result of the OkHttp's `ConnectionPool` pruning, but that doesn't mean that the connection was leaked there.

I'm looking into this now. It does seem that reading the `BufferedSource` to completion deallocates the connection (`RealBufferedSource.exhaused()` -> `StreamAllocation.streamFinished()` -> `StreamAllocation.deallocate()` -> `ConnectionPool.connectionBecameIdle()`).
I'm trying to see where else we can be leaking the connection by not closing the response.

**Comment by shawkins** [comment] 2022-12-13 10:15
> I'm not sure that the handler causing the leakage is the one for the AsyncBody (sendAsync) consumption

There are only 2 calls now.  Either one using asyncbody, or a websocket.  For there to be an issue with websockets, sendClose would not have to be called - as far as I'm aware non of that logic changed.  The change wrt asyncbody is that previously the sendAsync results were directly materialized by okhttp, now they are not.

> It is reported there as a result of the OkHttp's ConnectionPool pruning, but that doesn't mean that the connection was leaked there.

Isn't the reporting based upon the stack that was captured for a connection that was leaked?

> It does seem that reading the BufferedSource to completion deallocates the connection (RealBufferedSource.exhaused() -> StreamAllocation.streamFinished() -> StreamAllocation.deallocate() -> ConnectionPool.connectionBecameIdle()). So this would be evidence that the leakage is happening elsewhere.

I've confirmed the fix works - that is you can easily reproduce this scenario doing repeated reads.  At least with an integration test / real server (if you run against the mock server http1 will be used, I haven't confirmed if it has the same problem).  What I see is that when Http2Codec.read is called under exhausted, endOfInput is only called if an IOException is thrown from the FramingSource.  If it's just -1 being returned, then endOfInput is not called - so the auto close is not triggered.  Some of the http1 logic may be affected as well because I see the same read method in Http1Codec$AbstractSource.read.

**Comment by manusa** [comment] 2022-12-13 11:18
> Isn't the reporting based upon the stack that was captured for a connection that was leaked?

The reporting just says that a connection was leaking, not which one (at least this is what I get from reading the code in [`ConnectionPool`](https://github.com/square/okhttp/blob/06d38cb795d82d086f13c595a62ce0cbe60904ac/okhttp/src/main/java/okhttp3/ConnectionPool.java#L256-L284)

> Http2

I haven't checked with HTTP2, but I've validated that the connection is actually deallocated when read to exhaustion with the mock server (HTTP1).

I'll check with HTTP2 and see if I can provide a more realistic test to verify the fix.

**Comment by manusa** [comment] 2022-12-13 12:45
So it's confirmed, the issue is only present when using the HTTP 2 protocol. The PR (#4665) includes a test that verifies this against a fine-tuned OkHTTP Mock Server.

**Closed** 2022-12-13 13:45 UTC
Labels: bug
