### ISSUE TITLE
ServiceCatalogClient cannot created correct by new DefaultServiceCatalogClient()

### ISSUE THREAD

**Issue by a510431599** [fabric8io/kubernetes-client#2341] opened 2020-07-10 09:10 UTC
when using new DefaultServiceCatalogClient() to created a ServiceCatalogClient,it wont be working to do some method like list() or others.
its response code is 403 . i followed the debug , find out that it was because didnt add OpenShiftOAuthInterceptor into Interceptors when new DefaultServiceCatalogClient() .

when new DefaultOpenShiftClient():
![DefaultOpenShiftClient-1](https://user-images.githubusercontent.com/9293288/87137537-a629d680-c2cf-11ea-97e0-d42339955af3.png)
![DefaultOpenShiftClient-2](https://user-images.githubusercontent.com/9293288/87137544-a924c700-c2cf-11ea-8056-f914d21ad134.png)

but DefaultServiceCatalogClient :
![DefaultServiceCatalogClient](https://user-images.githubusercontent.com/9293288/87137602-bd68c400-c2cf-11ea-961a-35809179675f.png)

anyway,we can use new DefaultOpenShiftClient().adapt() instead.

thats what i find,if wrong,please tell me.

**Comment by rohanKanojia** [comment] 2020-07-29 10:07
@a510431599: Hi, I tried reproducing this issue on minishift but I wasn't able to do it. I tried listing all the `ServiceBroker` resources with this code but it worked for me:

```
try (ServiceCatalogClient client = new DefaultServiceCatalogClient()) {
    ServiceBrokerList serviceBrokerList = client.serviceBrokers().inAnyNamespace().list();

    System.out.println(serviceBrokerList.getItems().size() + " items found");
}
```
Could you please check if I missed something while reproducing this issue? I've created a reproducer project for this issue: https://github.com/r0haaaan/servicecatalog-client-demo

**Comment by manusa** [comment] 2020-08-05 09:05
We are closing now this issue since we're not able to reproduce. Feel free to reopen, or open a new issue if you are still affected by this problem.

**Closed by manusa** 2020-08-05 09:05 UTC
Labels: Waiting on feedback
