### ISSUE TITLE
CVE PRISMA-2022-0239 fix required in kubernetes-client 5.4.x

### ISSUE THREAD

**Issue by mkdev0101** [fabric8io/kubernetes-client#4331] opened 2022-08-10 12:18 UTC
### Describe the bug

There is a CVE reported in okhttp-3.14.9.jar which is packaged in kubernetes-client 5.4.2 . 

Details mentioned here : https://github.com/square/okhttp/issues/6738

This CVE is fixed in okhttp 4.10.x and need to be adopted in k8 client. 
Do we have a plan to fix this CVE on kubernetes client 5.4.x ?   

### Fabric8 Kubernetes Client version

5.4.2

### Steps to reproduce

https://github.com/square/okhttp/issues/6738

### Expected behavior

K8 client 5.4.x scan should not report the CVE https://github.com/square/okhttp/issues/6738 . 

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.22

### Environment

Linux

**Comment by bradbm** [comment] 2022-09-12 19:26
This looks like a duplicate of 
https://github.com/fabric8io/kubernetes-client/issues/4290

**Comment by manusa** [comment] 2022-09-16 07:08
Closing as duplicate

**Closed by manusa** 2022-09-16 07:08 UTC
Labels: duplicate
