### ISSUE TITLE
How to create a CronJob?

### ISSUE THREAD

**Issue by jorgesartori** [fabric8io/kubernetes-client#920] opened 2017-11-22 16:22 UTC
To create a deployment, I just invoke the method: KubernetesClient.extensions().deployments().createOrReplace(io.fabric8.kubernetes.api.model.extensions.Deployment);
So, I have a cronjob model created (io.fabric8.kubernetes.api.model.CronJob) but I didn't find a equivalent KubernetesClient method to create (or replace) it.

**Comment by rohanKanojia** [comment] 2018-07-10 10:38
Duplicate of #770

**Closed** 2018-07-10 10:38 UTC
