### ISSUE TITLE
There is unknown field "container" in Tekton

### ISSUE THREAD

**Issue by JINwonLEE** [fabric8io/kubernetes-client#1984] opened 2020-02-04 06:59 UTC
#### Issue description
I was trying to make Tekton `Task` with java fabric8.tekton apis, however I got some issues.

However I got an error message in runtime. 

![image](https://user-images.githubusercontent.com/18036257/73721122-e0161000-4766-11ea-9735-65862031d554.png)

#### Steps to reproduce the issue

I just compile with javac, and run the jar file. 

It is just sample test code, and there are already information about environments in link below. 

[issue in stackoverflow](https://stackoverflow.com/questions/60049533/there-is-unknown-field-container-in-tekton?noredirect=1#comment106205962_60049533)

#### What's the expected result?

- Make `Task` in tekton

#### What's the actual result?

- Got Error message as a screenshot provided.

**Comment by rohanKanojia** [comment] 2020-02-04 07:02
@JINwonLEE : Hi Jin, Thanks for you bug report. We'll try to get this fixed and update to latest tekton versions in coming release

**Comment by JINwonLEE** [comment] 2020-02-04 07:14
@rohanKanojia : Thanks for reply. Can I get some information or opinions about this issue? I have no idea how to figure it out. Thanks!!

**Comment by rohanKanojia** [comment] 2020-02-04 07:21
@Fabian-K  : polite ping, Do you have any idea about this? I haven't worked on tekton extension so can't give much feedback. Would appreciate if you could help out here

**Comment by Fabian-K** [comment] 2020-02-05 13:47
This seems to be a duplicate of https://github.com/fabric8io/kubernetes-client/issues/1900 

As far as I can see this is caused by the handling of embedded structs in go. A step in Tekton is basically a vanilla k8s container definition with (currently) one additional field for scripts. (https://github.com/tektoncd/pipeline/blob/v0.9.0/pkg/apis/pipeline/v1alpha1/task_types.go#L66-L73)

Serialization to JSON currently does not "union" all fields into one object. Instead, it creates an intermediate object for the vanilla k8s container definition. It should be like `{"image": "ubuntu","name":"test"}`, however its currently serialized as `{"container": {"image": "ubuntu","name":"test"}}`.

I don´t know why, but deserialization seems to handle this correctly -> it is possible to list tasks via the tekton client.

**Comment by JINwonLEE** [comment] 2020-02-06 01:26
@Fabian-K  Thanks for reply. 

As I understand, currently Tekton supports Script not Container. 

It means if I use `Script` instead of Container, then I could implement Tekton `Task` properly. 

Am I in right? if it does, I want to know how to use  `Script` because I cannot find a way to use `Script` with search. Can I have some docs or tutorial for that?

However I cannot fully understand that "list tasks via the tekton client" will make possible for implement `Task` in my example. Can I get more explanation? or some examples?


Thanks.

**Comment by JINwonLEE** [comment] 2020-02-06 12:30
@Fabian-K  I implemented some temporary code in tekton-model source code (`tekton-model-4.7.1.jar). 

Specifically, I add some properties for adding properties which is included in container(ex. name, image, command, args, ...) in `tekton-v1alpha1_Step` in schema(tekton-schema.json).

 It seems work when I run the code with the modified jar. I want to know the risk of adding the properties like above.  

Thanks.

**Comment by Fabian-K** [comment] 2020-02-07 17:00
AFAIK: the `tekton-schema.json` is a generated file based on the go model definitions. Therefore manually modifying it does not seem to be a good idea. Instead, the generator should be adjusted to properly handle embedded structs in go

**Comment by JINwonLEE** [comment] 2020-02-10 00:26
@Fabian-K  Ah.. I understand.. hmm... Then I have one more question. Can you give me the file name where go model definition? As I looked up the source code, I found generator file(`kubernetes-client/kubernetes-model/pkg/schemagen/generate.go`) which seems like generating schema. However I cannot find the object list(ex. Step, Task, Pipeline, ...) which would be target of generation. 

I think I have to look source code more deeply, but I want to get some guidelines for handling structs in go. Can I get some advices?

Thanks

**Comment by Fabian-K** [comment] 2020-02-19 10:25
Not sure if I understood you but if you want to add fields to the model definition that's not the way to go. The client uses the same model as e.g. tekton itself via go dependencies so the model can´t be changed.

**Closed** 2020-03-02 14:44 UTC
