### ISSUE TITLE
Update or create environment variable.

### ISSUE THREAD

**Issue by kfucGG** [fabric8io/kubernetes-client#5399] opened 2023-08-22 15:37 UTC
Hello guys, is your project have functionallity for updating existing environment variable value by name or If it not exists create it?

**Comment by rohanKanojia** [comment] 2023-08-22 17:07
@kfucGG : Is this a duplicate of https://github.com/fabric8io/kubernetes-client/issues/5394 ?

**Closed** 2023-08-22 18:00 UTC
