### ISSUE TITLE
upgrade okhttp 4.12

### ISSUE THREAD

**Issue by melin** [fabric8io/kubernetes-client#6109] opened 2024-07-05 03:20 UTC
### Is your enhancement related to a problem? Please describe

okhttp 3.12 version is older, the other library version is 4.12, easy to cause conflicts

### Describe the solution you'd like

upgrade okhttp 4.12

**Comment by rohanKanojia** [comment] 2024-07-11 06:30
Duplicate of https://github.com/fabric8io/kubernetes-client/issues/2632

Meanwhile you can check this workaround [here](https://github.com/fabric8io/kubernetes-client/blob/main/doc/KubernetesClientWithIPv6Clusters.md)

**Closed as completed** 2024-08-19 05:28 UTC
