### ISSUE TITLE
SharedIndexInformer with label filter only watching local Namespace

### ISSUE THREAD

**Issue by buehlmann** [fabric8io/kubernetes-client#2801] opened 2021-02-09 07:58 UTC
I'm trying to watch all events of ServiceAccounts with a specific Label in all Namespaces of a cluster. I register a SharedIndexInformer the following way:

```
            factory.sharedIndexInformerFor(
                    ServiceAccount.class,
                    ServiceAccountList.class,
                    new OperationContext().withLabels(Map.of(syncTokenLabelKey, syncTokenLabelValue)),
                    RESYNC_PERIOD_IN_MILLIS)
                    .addEventHandler(serviceAccountController);
```

But i get only informed for the configured Namespace instead of all Namespaces of the cluster. I'm testing against a local CRC OCP 4.5, run the app with `mvn quarkus:dev` using Quarkus 1.11.1, K8s Client 5.0.0.

**Comment by buehlmann** [comment] 2021-02-10 08:45
Update: It works if I create the `OperationContext` like that:
```
new OperationContext()
        .withIsNamespaceConfiguredFromGlobalConfig(true)
        .withLabels(Map.of(syncTokenLabelKey, syncTokenLabelValue)),
```

**Comment by rohanKanojia** [comment] 2021-03-11 20:43
I wasn't able to reproduce this on master. I've added two tests for SharedIndexInformer<ServiceAccount> for filter with labels in all namespace and in some specific namespace in #2895

**Comment by manusa** [comment] 2021-03-12 12:31
The way request URLs are build for Watch request was changed in the recent versions (however, you report the issue in 5.x)

This fix #2671 should be directly related with the issue which seems to be the same as #2668.

It also relates to: #2714

**Comment by rohanKanojia** [comment] 2021-03-12 14:20
This issue seems to be fixed via this PR : https://github.com/fabric8io/kubernetes-client/pull/2880 . Specifically this line:


https://github.com/fabric8io/kubernetes-client/blob/b3083a9ecdfe1f85445976a39d7820e09a9734d5/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationContext.java#L465

Here we while merging OperationContexts we pick `isNamespaceFromGlobalConfig`  if it's set to `true` in provided `OperationContext` argument. Otherwise, we just take whatever value is currently present in the current object.

Earlier we were just assigning argument value to current OperationContext's field, see[ v5.1.1 version ](https://github.com/fabric8io/kubernetes-client/blob/v5.1.1/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationContext.java#L376)

I can confirm that my minikube's current context contained a namespace in it:
```yaml
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Fri, 12 Mar 2021 15:45:33 IST
        provider: minikube.sigs.k8s.io
        version: v1.17.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
```

I tested it with this code:
```java
        try (KubernetesClient client = new DefaultKubernetesClient()) {
            SharedInformerFactory factory = client.informers();

            SharedIndexInformer<ServiceAccount> saInformer = factory.sharedIndexInformerFor(ServiceAccount.class,
                    new OperationContext().withLabels(Collections.singletonMap("foo", "bar")),
                    10 * 60 * 1000);

            saInformer.addEventHandler(new ResourceEventHandler<ServiceAccount>() {
                @Override
                public void onAdd(ServiceAccount serviceAccount) {
                    System.out.printf("ADDED %s/%s\n", serviceAccount.getMetadata().getNamespace(), serviceAccount.getMetadata().getName());
                }

                @Override
                public void onUpdate(ServiceAccount serviceAccount, ServiceAccount t1) {
                    System.out.printf("MODIFIED %s/%s\n", serviceAccount.getMetadata().getNamespace(), serviceAccount.getMetadata().getName());

                }

                @Override
                public void onDelete(ServiceAccount serviceAccount, boolean b) {
                    System.out.printf("DELETED %s/%s\n", serviceAccount.getMetadata().getNamespace(), serviceAccount.getMetadata().getName());
                }
            });

            factory.startAllRegisteredInformers();

            Thread.sleep(30 * 160 * 1000L);
        } catch (InterruptedException interruptedException) {
            interruptedException.printStackTrace();
        }
```
It prints the following output:
```
ADDED default/build-robot
MODIFIED default/build-robot
ADDED default/tutorial-service
MODIFIED default/tutorial-service
ADDED rokumar/build-robot
MODIFIED rokumar/build-robot
ADDED rokumar/tutorial-service
MODIFIED rokumar/tutorial-service
```

**Comment by manusa** [comment] 2021-05-24 09:05
I'm closing this issue since it seems to be fixed in our latest releases. Please, feel free to reopen in case the issue persists.

**Closed by manusa** 2021-05-24 09:05 UTC
