### ISSUE TITLE
Deleting deployment does  not delete associated pods 

### ISSUE THREAD

**Issue by mohanpindyala** [fabric8io/kubernetes-client#410] opened 2016-05-23 21:11 UTC
I am trying to delete deployment and its associated pods using following code 

`kubernetesClient
                .extensions()
                .deployments()
                .withLabels(labels).delete();`

It doesn't delete pods associated with it . Is there a alternative to delete pods too ?

where as when I delete using kubectl it deletes pods as well.

**Comment by jimmidyson** [comment] 2016-05-23 21:23
This _should_ be fixed in 1.3.92 which we released a few days ago. Are you using that version or an older one?

**Comment by mohanpindyala** [comment] 2016-05-23 21:24
I am using 1.3.92

**Comment by jimmidyson** [comment] 2016-05-24 21:15
Reproduced. Looks like we don't handle cascading deletes properly when we're deleting potential multiple resources, as `withLabels` implies. Working on a fix.

**Comment by ravilr** [comment] 2016-05-25 06:57
@jimmidyson 
As a workaround till your fix is released, explicitly scale each deployment to 0, and then delete, should also work right?

**Comment by jimmidyson** [comment] 2016-05-25 07:20
Good idea - that should work nicely.

**Closed** 2016-05-25 08:09 UTC

**Comment by mohanpindyala** [comment] 2016-05-25 16:41
thanks guys , let me try that in the meantime.
