### ISSUE TITLE
Eliptical Curve Keys not working

### ISSUE THREAD

**Issue by jevin36** [fabric8io/kubernetes-client#1057] opened 2018-04-13 11:56 UTC
Hi,
the official project had the same problem which was recently fixed. Are there any plan on fixing it in the fabric8io project as well?

Please see https://github.com/kubernetes-client/java/issues/135

**Comment by rohanKanojia** [comment] 2019-03-07 12:42
Duplicate of #1314

**Closed** 2019-03-07 12:42 UTC
