### ISSUE TITLE
Primitive default values working now, but enumeration won't

### ISSUE THREAD

**Issue by mteubner** [fabric8io/kubernetes-client#4674] opened 2022-12-14 13:25 UTC
### Describe the bug

The generation of the code is now working after fix for #4530 by #4536.

But the generation for enumeration defaults now creates a field with a String value.

    public enum State {

        @com.fasterxml.jackson.annotation.JsonProperty("STARTED")
        STARTED("STARTED"), @com.fasterxml.jackson.annotation.JsonProperty("STOPPED")
        STOPPED("STOPPED");

        java.lang.String value;

        State(java.lang.String value) {
            this.value = value;
        }
    }

    @com.fasterxml.jackson.annotation.JsonProperty("state")
    @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SKIP)
    private State state = "STARTED";

    public State getState() {
        return state;
    }

    public void setState(State state) {
        this.state = state;
    }

### Fabric8 Kubernetes Client version

6.3.0

### Steps to reproduce

1. Add a object with enumeration to your CRD, like 

              state:
                default: STARTED
                enum:
                - STARTED
                - STOPPED
                type: string

2. Generate the code

### Expected behavior

Field should not have quotation if object is an enumeration.

private State state = STARTED;

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3@latest

### Environment

Windows

**Comment by andreaTP** [comment] 2022-12-14 14:28
I think this is a duplicate of #4664 , submitted a fix for it 🙂 , here you are proposing a direct encoding but I believe that passing through serialization is somewhat "safer" in this case (e.g. imagine value names clashing across multiple enums)

**Closed** 2022-12-15 05:27 UTC
Labels: component/java-generator

**Comment by mteubner** [comment] 2022-12-15 08:11
@andreaTP Hello thank you for the fast answer. Sorry for not finding the fix. Yes this should work.
