### ISSUE TITLE
KubernetesServer mock should set the namespace of a resource being added

### ISSUE THREAD

**Issue by victornoel** [fabric8io/kubernetes-client#3265] opened 2021-06-23 06:59 UTC
Hi,

When running tests using `KubernetesServer`, and then with the client doing something like:
```java
var actualJob = client.batch().jobs()
                    .inNamespace(namespace)
                    .create(job);
```

If `job` didn't have the namespace set, then actualJob does not have its namespace set, while with an actual k8s API server, I believe it would be set.
I think the same happen if you fetch the jobs from the mock API server.

**Comment by shawkins** [comment] 2021-06-23 11:05
Duplicate of #3194

**Closed by shawkins** 2021-06-23 11:05 UTC

**Comment by victornoel** [comment] 2021-06-23 11:51
@shawkins nice, thx!

**Comment by victornoel** [comment] 2021-06-23 11:52
@shawkins also, any way to get it in 5.4.2 maybe? Or will 5.5 be released soon?

**Comment by shawkins** [comment] 2021-06-23 14:00
There's been a lot of changes to the mock server in 5.5, so it's not a quick hit to pull this into 5.4.2.  Since it seems like you are already looking for other things that are in 5.5 it would be simplest to just pick up that release.

**Comment by victornoel** [comment] 2021-06-23 14:03
@shawkins yep, totally agree, thx again :)
