### ISSUE TITLE
java.lang.IllegalStateException: No adapter available for type:class io.fabric8.kubernetes.client.BatchAPIGroupClient

### ISSUE THREAD

**Issue by TamerEzzeldin** [fabric8io/kubernetes-client#2845] opened 2021-02-26 06:37 UTC
Hi I am using fabric8 openshift-client version 5.1.0. I am trying to create a job, but I get this exception: java.lang.IllegalStateException: No adapter available for type:class io.fabric8.kubernetes.client.BatchAPIGroupClient
I tried also to use older versions of openshift-client but I get also the same exception.

**Comment by rohanKanojia** [comment] 2021-03-02 16:48
I'm not able to reproduce this. I tried creating a simple job like this[0]. Could you please share a sample reproducer project?

[0] https://github.com/rohanKanojia/kubernetes-client-demo/blob/master/src/main/java/io/fabric8/openshift/JobCreateExample.java

**Comment by TamerEzzeldin** [comment] 2021-03-02 18:48
Hi, solved!
The problem was, that only the openshift-client library was defined (as dependency) in the pom.xml file. It worked fine when I added also the kubernetes-client to the pom.xml file. Simply, both libraries are required, when dealing with openshift.

**Comment by rohanKanojia** [comment] 2021-03-03 06:38
Umm, this doesn't sound right to me. Let me try to reproduce with opeshift-client dependency only

**Comment by rohanKanojia** [comment] 2021-03-04 14:11
ohk, I tried again with a project with only `openshift-client` dependency but could not reproduce the issue. My reproducer project: https://github.com/r0haaaan/openshift-client-demo/blob/master/src/main/java/io/fabric8/demo/JobCreateExample.java

**Comment by rohanKanojia** [comment] 2021-03-05 08:51
@TamerEzzeldin : I think there might be some problem with your project. I wasn't able to reproduce this with a single `openshift-client` dependency too. Would appreciate if you could try out my demo project and provide feedback.

**Comment by rohanKanojia** [comment] 2021-03-05 10:01
I've created a PR to remove `kubernetes-client` from our `kubernetes-itests` so that both kubernetes and openshift tests work with just having `kubernetes-client`:

https://github.com/fabric8io/kubernetes-client/blob/00d23e8cece649c12e845e4032e7b5cd35071344/kubernetes-itests/pom.xml#L43-L47

**Comment by manusa** [comment] 2021-03-05 12:15
The #2875 PR proves that this might be a misconfiguration on the user's side.
Closing. Please feel free to open a new issue in case the problem persists.

**Closed** 2021-03-05 12:15 UTC
