### ISSUE TITLE
regression breaking mvn fabric8:apply: io.fabric8.kubernetes.client.KubernetesClientException: the namespace of the provided object does not match the namespace sent on the request

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#148] opened 2015-09-29 08:59 UTC
I now get the following in 2.2.35 when trying to do a `mvn fabric8:apply`

```
[INFO] --- fabric8-maven-plugin:2.2.35:apply (default-cli) @ jamesthingy ---
[INFO] Using kubernetes at: https://kubernetes.default.svc/ in namespace gogsadmin-jamesthingy-staging
[INFO] Kubernetes JSON: /var/jenkins_home/workspace/gogsadmin-jamesthingy/target/classes/kubernetes.json
[INFO] Is OpenShift: true
[INFO] Creating a namespace gogsadmin-jamesthingy-staging
[INFO] Created namespace: target/fabric8/applyJson/gogsadmin-jamesthingy-staging/namespace-gogsadmin-jamesthingy-staging.json
[INFO] Creating a template from kubernetes.json namespace default name jamesthingy
[ERROR] Failed to template entity from kubernetes.json. io.fabric8.kubernetes.client.KubernetesClientException: the namespace of the provided object does not match the namespace sent on the request. Template(apiVersion=v1, kind=Template, labels={}, metadata=ObjectMeta(annotations={description=Camel route using CDI in a standalone Java Container, fabric8.jamesthingy/summary=Camel route using CDI in a standalone Java Container, fabric8.jamesthingy/iconUrl=https://cdn.rawgit.com/fabric8io/fabric8/master/fabric8-maven-plugin/src/main/resources/icons/camel.svg}, creationTimestamp=null, deletionTimestamp=null, generateName=null, generation=null, labels={}, name=jamesthingy, namespace=gogsadmin-jamesthingy-staging, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), objects=[Service(apiVersion=v1, kind=Service, metadata=ObjectMeta(annotations={prometheus.io/port=9779, prometheus.io/scrape=true}, creationTimestamp=null, deletionTimestamp=null, generateName=null, generation=null, labels={container=java, component=jamesthingy, provider=fabric8, project=jamesthingy, version=1.0.1, group=quickstarts}, name=qs-java-camel-cdi, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=ServiceSpec(clusterIP=None, deprecatedPublicIPs=[], portalIP=null, ports=[ServicePort(name=null, nodePort=null, port=1, protocol=null, targetPort=null, additionalProperties={})], selector={container=java, project=jamesthingy, component=jamesthingy, provider=fabric8, group=quickstarts}, sessionAffinity=null, type=null, additionalProperties={}), status=null, additionalProperties={}), ReplicationController(apiVersion=v1, kind=ReplicationController, metadata=ObjectMeta(annotations={fabric8.io/build-id=1}, creationTimestamp=null, deletionTimestamp=null, generateName=null, generation=null, labels={container=java, component=jamesthingy, provider=fabric8, project=jamesthingy, version=1.0.1, group=quickstarts}, name=jamesthingy, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=ReplicationControllerSpec(replicas=1, selector={container=java, component=jamesthingy, provider=fabric8, project=jamesthingy, version=1.0.1, group=quickstarts}, template=PodTemplateSpec(metadata=ObjectMeta(annotations={}, creationTimestamp=null, deletionTimestamp=null, generateName=null, generation=null, labels={container=java, component=jamesthingy, provider=fabric8, project=jamesthingy, version=1.0.1, group=quickstarts}, name=null, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[Container(args=[], command=[], env=[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=metadata.namespace, additionalProperties={}), additionalProperties={}), additionalProperties={})], image=docker.io/fabric8/jamesthingy:1.0.1, imagePullPolicy=null, lifecycle=null, livenessProbe=null, name=jamesthingy, ports=[ContainerPort(containerPort=8778, hostIP=null, hostPort=null, name=jolokia, protocol=null, additionalProperties={})], readinessProbe=null, resources=null, securityContext=SecurityContext(capabilities=null, privileged=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, additionalProperties={}), stdin=null, terminationMessagePath=null, tty=null, volumeMounts=[], workingDir=null, additionalProperties={})], dnsPolicy=null, host=null, hostNetwork=null, imagePullSecrets=[], nodeName=null, nodeSelector={}, restartPolicy=null, serviceAccount=null, serviceAccountName=null, terminationGracePeriodSeconds=null, volumes=[], additionalProperties={}), additionalProperties={}), additionalProperties={}), status=null, additionalProperties={})], parameters=[], additionalProperties={})
io.fabric8.kubernetes.client.KubernetesClientException: the namespace of the provided object does not match the namespace sent on the request
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.assertResponseCode(BaseOperation.java:493)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleResponse(BaseOperation.java:506)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:520)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:208)
	at io.fabric8.kubernetes.api.Controller.doCreateTemplate(Controller.java:355)
	at io.fabric8.kubernetes.api.Controller.installTemplate(Controller.java:346)
	at io.fabric8.kubernetes.api.Controller.applyTemplate(Controller.java:308)
	at io.fabric8.maven.ApplyMojo.applyTemplates(ApplyMojo.java:256)
	at io.fabric8.maven.ApplyMojo.execute(ApplyMojo.java:197)
```

**Comment by iocanel** [comment] 2015-09-29 09:10
Not sure if its a client thing or if its a maven plugin thing. Either way I am on it.

**Comment by iocanel** [comment] 2015-09-29 11:50
I think that the root cause of this issue is that we have (at least) 3 different places where we try to find a sensible default value for namespace:

i) client config (kubeconfig < env var < system prop < explicit value)
ii) kubernetes helper (kubeconfig < env var < system prop)
iii) apply mojo (env var < explicit value)

imho, we should only use (i) and make sure we align values inside the apply mojo when the user explicitly specifies a namespace.

**Comment by jstrachan** [comment] 2015-09-29 12:17
I'm happy to use i) only for the default; but we still need to allow an explicit namespace to be specified in the mvn plugins; so maybe the default maven property value should be empty string?

**Comment by iocanel** [comment] 2015-09-29 13:19
I pushed a fix on fabric8 master, which should fix all of the above.

**Closed by iocanel** 2015-09-29 13:19 UTC
