### ISSUE TITLE
retrieval of imagestreamtags do not appear to work with the v3.x client

### ISSUE THREAD

**Issue by gabemontero** [fabric8io/kubernetes-client#1046] opened 2018-03-27 16:43 UTC
see see https://github.com/fabric8io/jenkins-sync-plugin/pull/12#issuecomment-366088791

and most recently https://github.com/fabric8io/jenkins-sync-plugin/pull/12#issuecomment-366337554

@hrishin @rupalibehera FYI

**Comment by hrishin** [comment] 2018-03-29 06:41
@gabemontero Thanks for raising this issue. Which OpenShift version you have used to get `imagestreamtags`?

cc: @piyush1594

**Comment by piyush1594** [comment] 2018-03-29 06:53
@hrishin This seems like an issue which affected FMP too

**Comment by hrishin** [comment] 2018-03-29 07:25
@piyush1594 could you refer an issue from F8MP for this?

**Comment by piyush1594** [comment] 2018-03-29 08:58
Hey @hrishin i am talking about this https://github.com/fabric8io/fabric8-maven-plugin/pull/1225

**Comment by piyush1594** [comment] 2018-03-29 12:33
@gabemontero From the issue comments you mentioned, it seems like an error with client 3.0.3 onwards.

**Comment by gabemontero** [comment] 2018-03-29 13:36
that is correct @piyush1594 ... 3.0.x onward 

it works with v2.3.1 of the fabric client

@hrishin - answers to your questions:

1) we were testing against v3.9 of openshift ... the GA of that version just landed earlier this week

2) we produced it running the plugin extended tests we've discussed previously
   a) long term, you guys really need to get to a point where you can run this, if your are still having problems after the various instruction details I sent, the only other thing I can think of is to have a bluejeans session and try to sort it out live 

    or you can get PR https://github.com/fabric8io/jenkins-sync-plugin/pull/12 to a point where you guys have our latest stuff, and then we can start submitting your new features against upstream 

   b) short term, if you can at least get a 3.9 openshift environment up in however way you get it up, to execute the failing test, run
     i) oc create -f https://raw.githubusercontent.com/openshift/origin/master/test/extended/testdata/imagestreamtag-jenkins-slave-pods.yaml
     ii) oc new-app -f https://raw.githubusercontent.com/openshift/origin/master/test/extended/testdata/jenkins-slave-template.yaml
     iii) oc start-build openshift-jee-sample
     
    the corresponding jenkins job run failed for us because the imagestreamtag could not be retrieved 

    See https://github.com/fabric8io/jenkins-sync-plugin/pull/12#issuecomment-366088791 on the type of debug I added to confirm that we could not retrieve the imagestreamtag

**Comment by piyush1594** [comment] 2018-04-04 11:58
Hey @gabemontero,

Thanks for the information. I just added a PR of the examples in FKC #1050 

This PR contains the example for building the imageStream and imagStreamTags. 

What I have figured out is ImageStream is working fine for any version of OpenShift using any version of Client. You can check by running the example which is creating the same imageStream as mentioned in your yaml. Even fetching tags from imageStream is also working.

But creating/fetching imageStreamTag is not working with the latest version of FKC, whether OpenShift 3.7.0 or 3.9.0 

Fetching List of ImageStreamTag is just returning an empty list.

The error I am getting is this

```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:383)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:770)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:195)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:162)
	at io.fabric8.openshift.examples.ImageStreamTagExample.main(ImageStreamTagExample.java:50)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for kind:DockerImage
 at [Source: java.io.BufferedInputStream@38467116; line: 1, column: 4034] (through reference chain: io.fabric8.openshift.api.model.ImageStreamTag["image"]->io.fabric8.openshift.api.model.Image["dockerImageMetadata"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:982)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:56)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:31)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2874)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:235)
	... 9 more
```

**Comment by gabemontero** [comment] 2018-04-04 15:14
Yes @piyush1594 you have reproduced what I have originally encountered.  And to reiterate, we don't see this problem with the 2.3.1 client.

I previously did not get the exception you have noted.  Perhaps you've turned on trace, modified the client to report the error, or are running with an even later version that logs the exception ?

Whatever the answer, certainly that exception would seem to provide a clue.  In particular:

`No resource type found for kind:DockerImage`

I can tell you that from an openshift api perspective, this kind is valid.  See https://github.com/openshift/api/blob/master/image/v1/types.go#L210-L213

And it has been that way for quite a while.

Something must have broke with the associate kubernetes-model (or wherever the openshift version of that is), where the one used with the v2.3.1 client is good here and the one used with the later clients is not.

I would suggest that you tag / pull in the folks who have maintained that repo(s) in the past

**Comment by piyush1594** [comment] 2018-04-05 19:52
So after debugging a little bit more,

The problem happens when the request is made to the cluster, it is executed and when you get the response, it is not able to unmarshal that.

The API call that is getting made to the cluster looks fine to me. As I tried to create an imageStream tag, the call is getting made perfectly, the resource is also getting created there and returns the response which it is unable to unmarshal and returns the error which seems like the tag is not created but if you go on the cluster and check, it is there.

Similarly, it is making a get call perfectly, but the response is not getting properly unmarshalled and returning the error seems like the tag is not working and no output.

Seems like the response body which is returned is not according to clients classes. Need to debug more to get on to this. Mainly it is throwing error at this https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L383

**Comment by piyush1594** [comment] 2018-04-09 07:32
Hey @gabemontero @hrishin 

Just found this on model https://github.com/fabric8io/kubernetes-model/issues/296 Looks relevant to this.

**Comment by gabemontero** [comment] 2018-04-09 15:30
Yep I agree @piyush1594 - that is what we are shooting.  And as I noted multiple times when discussing this, fixing the model code that the fabric8 kubernetes/openshfit client code is using is what is required.

What is unclear to me is whether the ImageStreamTag stuff is in kubernetes-model, or this repo. or some other openshift equivalent repo.  `ImageStreamTag` is an openshift api object, not an kubernetes one.

But I'm assuming either you or @iocanel or one of the other typical maintainers of this code will know that and can educate me :-)

**Comment by piyush1594** [comment] 2018-04-09 19:11
@gabemontero 

Kubernetes-model will generate both the openshift and kubernetes API objects. Kubernetes Client uses Kubernetes-model for all the objects.

**Comment by piyush1594** [comment] 2018-04-11 18:57
Hey @gabemontero @hrishin 

PR is here on model https://github.com/fabric8io/kubernetes-model/pull/302 which will fix this as we support new Model in the client. 

I will send a PR soon here as the model is released with new model version and also a test regarding this. I checked this locally and its working.

Thanks

**Comment by gabemontero** [comment] 2018-04-11 19:05
Thanks for the update @piyush1594 - it looks like we are getting closer :-)

**Comment by piyush1594** [comment] 2018-04-17 19:52
Hey @gabemontero 

PR on the model is merged https://github.com/fabric8io/kubernetes-model/pull/302. Soon we will release the model(which is blocked on https://github.com/openshiftio/openshift.io/issues/2825) and as the new version will get reflected here, this will work. Meanwhile added unit and regression test for ImageStreamTag here #1060 and Example for this has already been added.

Thanks

**Comment by gabemontero** [comment] 2018-04-18 13:35
Thanks for the udpate @piyush1594 

We'll try to track those items you listed as well, but certainly please continue to keep us up to speed on things.  As soon as it is ready, we'll try to bump the k8s client in openshift sync plugin and let you know the results.

@bparees @coreydaley fyi ^^

**Comment by hrishin** [comment] 2018-04-20 05:33
> Thanks for the udpate @piyush1594

:+1: 

> We'll try to track those items you listed as well, but certainly please continue to keep us up to speed on things. As soon as it is ready, we'll try to bump the k8s client in openshift sync plugin and let you know the results.

@gabemontero 
we got stucked on release because of some technical issue on fabric8 Jenkins setup. But will get it release as soon as possible.

cc: @jaseemabid

**Comment by piyush1594** [comment] 2018-04-26 18:59
@gabemontero @hrishin 

Kubernetes Model 2.0.9 got released today, the new version has been reflected here. After reflecting new version #1060 also worked. Hope someone will review and merge that soon.

Will try to do the release of client asap.

Thanks

**Comment by gabemontero** [comment] 2018-04-26 19:03
thanks for the update @piyush1594

**Comment by piyush1594** [comment] 2018-04-27 08:52
closing this as #1060 is merged. Time to release client

**Closed** 2018-04-27 08:52 UTC
Labels: bug

**Comment by gabemontero** [comment] 2018-04-27 12:40
What release of the client should we look for?  Or where can you look/monitor to find out when the client version with the fix is released?

**Comment by piyush1594** [comment] 2018-04-27 13:09
Hey,

We will throw a mail to https://groups.google.com/forum/#!forum/fabric8-devclients google group whenever new release happens and also all the fixes in that. You can join this.

We will update the git tag with release notes.

Thanks

**Comment by gabemontero** [comment] 2018-05-01 15:35
OK thanks for the heads up @piyush1594 

@bparees @coredaley FYI ... we have a new k8s client to try and pull in for https://trello.com/c/9882Gnrt/1488-3-update-fabric-k8s-client-in-jenkins-sync-plugin-jenkinsintegration, confirm it can get ISTs any anything else sync plugin is dealing with
