### ISSUE TITLE
VersionInfo contains null data in OpenShift 4.6

### ISSUE THREAD

**Issue by vsevel** [fabric8io/kubernetes-client#3189] opened 2021-05-28 18:33 UTC
This issue has been found in `5.4.0`, which is used in Quarkus `2.0.0.CR1`. And it is a regression compared to `5.3.1`, which was used in Quarkus `2.0.0.Alpha3`.

With the following code:

```
    @Inject
    @Privileged
    OpenShiftClient privilegedClient;
...
            VersionInfo version = privilegedClient.getVersion();
            String major = version.getMajor();
            log.info("Version Major " + major);
            log.info("Version Minor " + version.getMinor());
            log.info("Version BuildDate " + version.getBuildDate());
```

In `5.3.1` I see:

```
2021-04-30 17:21:55,966 INFO  [com.x.arte.ocpdeploy.deploy.ContextMgr] (main) Version Major 4
2021-04-30 17:21:56,011 INFO  [com.x.arte.ocpdeploy.deploy.ContextMgr] (main) Version Minor 6.13
2021-04-30 17:21:56,012 INFO  [com.x.arte.ocpdeploy.deploy.ContextMgr] (main) Version BuildDate Tue Feb 02 14:55:04 GMT 2021
```

In `5.4.0` I see:
```
2021-05-28 19:46:36,567 INFO  [com.x.arte.ocpdeploy.deploy.ContextMgr] (main) Version Major null
2021-05-28 19:46:36,568 INFO  [com.x.arte.ocpdeploy.deploy.ContextMgr] (main) Version Minor null
2021-05-28 19:46:36,568 INFO  [com.x.arte.ocpdeploy.deploy.ContextMgr] (main) Version BuildDate null
```

**Comment by matthyx** [comment] 2021-05-31 08:18
possibly fixed by https://github.com/fabric8io/kubernetes-client/pull/3175 ?

**Comment by rohanKanojia** [comment] 2021-05-31 09:51
Not 100% sure since #3175 seems to fix non release OpenShift versions `4.8.0-0.nightly-2021-05-26-071911`

**Comment by matthyx** [comment] 2021-05-31 09:55
I have started a huge comparison between 5.3.1 and 5.4.0 trying to see what's changed regarding the versions but no success so far :(

**Comment by rohanKanojia** [comment] 2021-06-01 04:37
ohk, I tried reproducing this and I was able to reproduce this. it's happening on my 4.7.2 cluster as well

**Comment by matthyx** [comment] 2021-06-01 05:17
> ohk, I tried reproducing this and I was able to reproduce this. it's happening on my 4.7.2 cluster as well
Awesome, did you try with master as well ? 

At first I thought it was permission issues with the service account, but I'm able to curl "apis/config.openshift.io/v1/clusterversions" within a container... and of course unit tests are working well.

It's not so easy for me to play with different versions, as our app now uses Quarkus and it's a bit of #dependencyhell to force the framework using my custom build.

**Comment by rohanKanojia** [comment] 2021-06-01 06:56
I think this behavior was introduced by https://github.com/fabric8io/kubernetes-client/pull/3049 . 

We seem to have minor problem in our code which was exposed by this PR. We are calculating openshift 4 version as a fallback when old openshift version apicall fails:

https://github.com/fabric8io/kubernetes-client/blob/1a61f0c83b681d06482e6f5af919f46e8a73e188/openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftClusterOperationsImpl.java#L41-L48

However, in ClusterOperationsImpl we're not checking the response code or whether our response was even successful before assigning to map. Earlier since there was no null check so code used to throw NPE in case of a 404 response body since it won't contain Version data and that NPE was caught by OpenShiftClusterOperationsImpl

**Comment by matthyx** [comment] 2021-06-01 07:01
ahah, I knew it was related to NPE somehow, just couldn't verify it, good job @rohanKanojia !!!!!

Will you be able to include this as well into the patch release 5.4.1 in time for Quarkus release, please?

**Closed** 2021-06-01 10:10 UTC

**Comment by manusa** [comment] 2021-06-01 15:03
> Will you be able to include this as well into the patch release 5.4.1 in time for Quarkus release, please?

https://github.com/quarkusio/quarkus/pull/17598
