### ISSUE TITLE
withFormat method has no effect

### ISSUE THREAD

**Issue by Neoware** [fabric8io/kubernetes-client#1445] opened 2019-03-19 10:00 UTC
Hi and thank you for the great library ! 

I faced an issue when creating a container on my 0.34.1 minikube. I try to use the resource requests for my pod using a construct like this: 

```
      val container =
        new ContainerBuilder()
          ...
          .withNewResources()
          .withRequests(new util.HashMap[String, Quantity]() {
            {
              put("cpu", new QuantityBuilder()
                .withAmount("50")
                .withFormat("m")
                .build())
              put("memory", new QuantityBuilder()
                .withAmount("128")
                .withFormat("Mi")
                .build())
            }
          })
          .endResources()
          ...
          .build
```

(This way of doing things was taken from https://github.com/fabric8io/kubernetes-client/blob/081c1ad0110c15557306fd3ec8d3734e82508448/kubernetes-model/kubernetes-model/src/test/java/io/fabric8/kubernetes/api/model/BuildConfigTest.java)

The problem is, the `withFormat` method seems to have no effect since when I look at the pod with a kubectl describe pod {podName} I see this:

```
  Requests:
      cpu:      50
      memory:   128

```
 And of course, my pod is then pending and cannot be scheduled because my cluster doesn't have 50 cpus when I only wanted 50 millicpus. Maybe that's not how I'm supposed to do this so feel free to correct me if it's necessary!

Thank you in advance for taking a look at this issue :)

**Comment by slandelle** [comment] 2019-03-20 13:34
This is a duplicate of #885

**Comment by yaaoing** [comment] 2019-04-09 07:13
You can try this:
`limit.put("cpu", new QuantityBuilder().withAmount("1").build());`
`limit.put("memory", new QuantityBuilder().withAmount("2Gi").build());`

**Comment by rohanKanojia** [comment] 2019-08-06 12:33
Duplicate of #885

**Closed by rohanKanojia** 2019-08-06 12:33 UTC
