### ISSUE TITLE
Custom Resource Definition from YAML: client.load(CRD).get() --> nullPointerException

### ISSUE THREAD

**Issue by nikkatalnikov** [fabric8io/kubernetes-client#1462] opened 2019-03-28 00:36 UTC
Hello, I am using Scala and Spark-operator and getting NPE while doing:

```scala
  val client = new DefaultKubernetesClient()
  KubernetesDeserializer.registerCustomKind("sparkoperator.k8s.io/v1beta1", "SparkApplication", classOf[CustomObject])
  private val loaded = client.load(convertYamlToJson(resourceName)).get()
```

at the last line ^^

Jackson itself works fine and validates each field.

```scala
case class CustomObject @JsonCreator() (@JsonProperty("spec") spec: Spec,
                                        @JsonProperty("status") status: Option[Status]) extends CustomResource

@JsonIgnoreProperties(Array("restartPolicy"))
case class Spec @JsonCreator() (@JsonProperty("type") `type`: String,
                                @JsonProperty("mode") mode: String,
                                @JsonProperty("image") image: String,
                                @JsonProperty("imagePullPolicy") imagePullPolicy: String,
                                @JsonProperty("mainApplicationFile") mainApplicationFile: String,
                                @JsonProperty("mainClass") mainClass: String,
                                @JsonProperty("driver") driver: Driver,
                                @JsonProperty("executor") executor: Executor,
                                @JsonProperty("sparkVersion") sparkVersion: String)

case class Driver @JsonCreator() (@JsonProperty("cores") cores: Double,
                                  @JsonProperty("coreLimit") coreLimit: String,
                                  @JsonProperty("memory") memory: String,
                                  @JsonProperty("serviceAccount") serviceAccount: String,
                                  @JsonProperty("labels") labels: Labels)

case class Executor @JsonCreator() (@JsonProperty("cores") cores: Double,
                                    @JsonProperty("instances") instances: Double,
                                    @JsonProperty("memory") memory: String,
                                    @JsonProperty("labels") labels: Labels)

case class Labels @JsonCreator() (@JsonProperty("version") version: String)

case class Status @JsonCreator() (@JsonProperty("applicationState") applicationState: ApplicationState,
                                  @JsonProperty("submissionAttempts") submissionAttempts: Int,
                                  @JsonProperty("lastSubmissionAttemptTime") lastSubmissionAttemptTime: String,
                                  @JsonProperty("terminationTime") terminationTime: Option[String],
                                  @JsonProperty("sparkApplicationId") sparkApplicationId: Option[String],
                                  @JsonProperty("executionAttempts") executionAttempts: Option[Int],
                                  @JsonProperty("driverInfo") driverInfo: DriverInfo)

case class DriverInfo @JsonCreator() (@JsonProperty("podName") podName: Option[String],
                                      @JsonProperty("webUIPort") webUIPort: Option[Int],
                                      @JsonProperty("webUIServiceName") webUIServiceName: Option[String])

case class ApplicationState @JsonCreator() (@JsonProperty("state") state: String,
                                            @JsonProperty("errorMessage") errorMessage: String)
```

YAML:

```yaml
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus"
  imagePullPolicy: Always
  mainClass: consumer.KafkaConsumer
  mainApplicationFile: "http://192.168.0.104:8080/myjar.jar"
  sparkVersion: "2.4.0"
  restartPolicy:
    type: Never
  driver:
    cores: 0.1
    coreLimit: 1000m
    memory: 1024m
    labels:
      version: 2.4.0
    serviceAccount: default
  executor:
    cores: 1
    instances: 1
    memory: 1024m
    labels:
      version: 2.4.0
```

What am I doing wrong?

Stacktrace:

```
[info] it_tests.KafkaTest *** ABORTED ***
[info]   java.lang.NullPointerException:
[info]   at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.acceptVisitors(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:289)
[info]   at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:281)
[info]   at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:64)
```

**Comment by nikkatalnikov** [comment] 2019-04-02 16:36
anyone?

**Comment by rohanKanojia** [comment] 2019-04-03 16:18
@nikkatalnikov : Hi, I'm working on improving custom resource support #1472

**Comment by rohanKanojia** [comment] 2019-04-03 16:41
bdw, I'm not familiar with this way of creating custom resources. As far as I know you need to provide Pojos to the client for operations. Please take a look at https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java

**Comment by nikkatalnikov** [comment] 2019-04-07 13:29
@rohanKanojia looks like `rawCustomResource` is what I need.

**Comment by rohanKanojia** [comment] 2019-04-10 14:58
@nikhil-thomas : awesome, Could you please try out our master SNAPSHOT build and provide some feedback on how it can be improved? bdw, current PR is merged and it would be available in coming release ;-)

**Comment by dkc-bitsian** [comment] 2019-04-16 00:38
@nikkatalnikov` - I ran into the same issue. The reason for the null pointer exception is because `metadata:
  name: spark-pi
  namespace: default . `
is not defined anywhere. 
Can i know how you got around this issue ?

**Comment by rohanKanojia** [comment] 2019-04-16 06:21
@nikkatalnikov @dkc-bitsian : bdw, 4.2.1 is released, you can try creating custom resource like this: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java

**Comment by dkc-bitsian** [comment] 2019-04-16 22:33
@rohanKanojia  Got an error using that method
`
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Bad Request] with root cause

java.lang.IllegalStateException: Bad Request
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:150) ~[kubernetes-client-4.2.1.jar!/:?]
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.validateAndSubmitRequest(RawCustomResourceOperationsImpl.java:159) ~[kubernetes-client-4.2.1.jar!/:?]
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.create(RawCustomResourceOperationsImpl.java:55) ~[kubernetes-client-4.2.1.jar!/:?]
`

Code block is as follows
`
KubernetesClient client = new DefaultKubernetesClient();
        String jsonObject = new JSONObject().put("apiVersion", "sparkoperator.k8s.io/v1beta1").put("kind", "SparkApplication")
                .put("metadata", new JSONObject().put("name", "spark-pi-test-1").put("namespace", "namespace")).put("spec", new JSONObject().put("type", "Scala")
                        .put("mode", "cluster").put("image", "imagepath")
                        .put("imagePullPolicy", "Always").put("mainClass", "Application").put("mainApplicationFile", "local:///amerigo/jars/sparktest-1.0-SNAPSHOT-jar-with-dependencies.jar")
                        .put("driver", new JSONObject().put("serviceAccount", "spark-service-account"))).toString();


        CustomResourceDefinitionContext customResourceDefinitionContext = new CustomResourceDefinitionContext.Builder()
                .withName("sparkapplications.sparkoperator.k8s.io")
                .withGroup("sparkoperator.k8s.io")
                .withVersion("v1beta1")
                .withPlural("sparkapplications")
                .withScope("Cluster")
                .build();

        Map<String, Object> object = client.customResource(customResourceDefinitionContext).create("namespace", jsonObject);
      `

**Comment by dkc-bitsian** [comment] 2019-04-16 22:35
`
`

Code block is as follows`KubernetesClient client = new DefaultKubernetesClient();
        String jsonObject = new JSONObject().put("apiVersion", "sparkoperator.k8s.io/v1beta1").put("kind", "SparkApplication")
                .put("metadata", new JSONObject().put("name", "spark-pi-test-1").put("namespace", "namespace")).put("spec", new JSONObject().put("type", "Scala")
                        .put("mode", "cluster").put("image", "imagepath")
                        .put("imagePullPolicy", "Always").put("mainClass", "Application").put("mainApplicationFile", "local:///amerigo/jars/sparktest-1.0-SNAPSHOT-jar-with-dependencies.jar")
                        .put("driver", new JSONObject().put("serviceAccount", "spark-service-account"))).toString();


        CustomResourceDefinitionContext customResourceDefinitionContext = new CustomResourceDefinitionContext.Builder()
                .withName("sparkapplications.sparkoperator.k8s.io")
                .withGroup("sparkoperator.k8s.io")
                .withVersion("v1beta1")
                .withPlural("sparkapplications")
                .withScope("Cluster")
                .build();

        Map<String, Object> object = client.customResource(customResourceDefinitionContext).create("namespace", `jsonObject);``

**Comment by rohanKanojia** [comment] 2019-04-17 07:12
@dkc-bitsian : Could you please share yaml for this spark operator CRD so that I can reproduce it on my machine?

**Comment by rohanKanojia** [comment] 2019-04-24 05:34
@dkc-bitsian : Did you get time to get back on this? As far as I can suspect it looks like there is some problem in your object itself. Are you able to apply same object onto api server using  `kubectl apply -f`?

**Comment by rohanKanojia** [comment] 2019-04-24 05:39
@dkc-bitsian @nikkatalnikov : Sorry, I don't have much idea about what spark is. But I would be able to help if provided a reproducible use case(i.e CRD yaml and code which is creating custom resource(already shared)

**Comment by rohanKanojia** [comment] 2019-05-06 17:33
Closing this one. Feel free to re-open if facing any problems

**Closed by rohanKanojia** 2019-05-06 17:33 UTC

**Comment by wrbriggs** [comment] 2019-07-26 16:47
@dkc-bitsian No idea if this is helpful at this point, since the issue is closed, and my example is in Scala, but after a significant amount of debugging how these things were being translated into the K8s HTTP API, I was able to submit a Spark job with the fabric8 client, using the following code:

```
val customResourceDefinitionContext = new CustomResourceDefinitionContext.Builder()
    .withVersion("v1beta1")
    .withPlural("sparkapplications")
    .withScope("Namespaced")
    .withGroup("sparkoperator.k8s.io")
    .build();

  val crdResult = fabric8Client.customResource(customResourceDefinitionContext)

  val runResult = crdResult.createOrReplace("default", new FileInputStream(args(0)))
```

**Comment by wrbriggs** [comment] 2019-07-26 16:52
@rohanKanojia It looks like @dkc-bitsian didn't get back to you with this info, but I'm providing the output of a `kubectl describe customresourcedefinition sparkapplications.sparkoperator.k8s.io` to help with any future debugging this issue might require:
```
Name:         sparkapplications.sparkoperator.k8s.io
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2019-06-24T14:42:45Z
  Generation:          1
  Resource Version:    698
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/sparkapplications.sparkoperator.k8s.io
  UID:                 5407d444-968e-11e9-bf29-0aafc653b9e0
Spec:
  Additional Printer Columns:
    JSON Path:    .metadata.creationTimestamp
    Description:  CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    Name:  Age
    Type:  date
  Group:   sparkoperator.k8s.io
  Names:
    Kind:       SparkApplication
    List Kind:  SparkApplicationList
    Plural:     sparkapplications
    Short Names:
      sparkapp
    Singular:  sparkapplication
  Scope:       Namespaced
  Validation:
    Open APIV 3 Schema:
      Properties:
        Metadata:
          Properties:
            Name:
              Max Length:  63
              Min Length:  1
              Type:        string
        Spec:
          Properties:
            Deps:
              Properties:
                Download Timeout:
                  Minimum:  1
                  Type:     integer
                Max Simultaneous Downloads:
                  Minimum:  1
                  Type:     integer
            Driver:
              Properties:
                Cores:
                  Exclusive Minimum:  true
                  Minimum:            0
                  Type:               number
                Pod Name:
                  Pattern:  [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
            Executor:
              Properties:
                Cores:
                  Exclusive Minimum:  true
                  Minimum:            0
                  Type:               number
                Instances:
                  Minimum:  1
                  Type:     integer
            Mode:
              Enum:
                cluster
                client
            Monitoring:
              Properties:
                Prometheus:
                  Properties:
                    Port:
                      Maximum:  49151
                      Minimum:  1024
                      Type:     integer
            Python Version:
              Enum:
                2
                3
            Restart Policy:
              Properties:
                On Failure Retries:
                  Minimum:  0
                  Type:     integer
                On Failure Retry Interval:
                  Minimum:  1
                  Type:     integer
                On Submission Failure Retries:
                  Minimum:  0
                  Type:     integer
                On Submission Failure Retry Interval:
                  Minimum:  1
                  Type:     integer
                Type:
                  Enum:
                    Never
                    OnFailure
                    Always
            Type:
              Enum:
                Java
                Scala
                Python
                R
  Version:  v1beta1
  Versions:
    Name:     v1beta1
    Served:   true
    Storage:  true
Status:
  Accepted Names:
    Kind:       SparkApplication
    List Kind:  SparkApplicationList
    Plural:     sparkapplications
    Short Names:
      sparkapp
    Singular:  sparkapplication
  Conditions:
    Last Transition Time:  2019-06-24T14:42:45Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  <nil>
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1beta1
Events:  <none>
```
The official definition can also be found [in the manifest](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/manifest/spark-operator-crds.yaml)  of the [spark-on-k8s-operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator) project.
