### ISSUE TITLE
is there have some toolkits can convert crd yaml file to fabric8 java file

### ISSUE THREAD

**Issue by chestarss** [fabric8io/kubernetes-client#3781] opened 2022-01-25 07:48 UTC
### Is your enhancement related to a problem? Please describe

is there have some generator toolkits for third-part crd yaml file to fabric8 java client code file

### Describe the solution you'd like

which like https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md

**Comment by rohanKanojia** [comment] 2022-01-25 08:42
@chestarss : Do you mean you want to convert CRD Yaml to a Java Pojo (#3642 ) ? We are very close to merging one of these https://github.com/fabric8io/kubernetes-client/pull/3693 features

**Comment by chestarss** [comment] 2022-01-25 09:20
> 

thanks very much

**Comment by rohanKanojia** [comment] 2022-01-25 09:45
Duplicate of #3642

**Closed** 2022-01-25 12:34 UTC
Labels: question
